### ISSUE TITLE
프로젝트 CI 설정

### ISSUE THREAD

**Issue by ktk1012** [sparcs-kaist/sparcs09#25]
#20 과 연관되는 이슈로 자동 배포를 하기 이전에 기본적인 CI가 될 수 있도록 합니다.

**Comment by ktk1012** [comment]
https://www.caktusgroup.com/blog/2015/08/15/making-clean-code-part-your-build-process/
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

eslint와 pyflake 체크 정도는 PR 단계에서 수행하면 좋을 듯 합니다. (테스트까진 못하더라도..)

**Comment by samjo-nyang** [comment]
lint, flake check 까지 해서 초기 ci 설정 완료했습니다. 자동 배포는 별도 이슈로 진행하면 될 것 같습니다.
