### ISSUE TITLE
Vue js 프로젝트 구조 잡기

### ISSUE THREAD

**Issue by ktk1012** [sparcs-kaist/sparcs09#34]
* vue.js 각 요소들에 대한 project 구조 작성
    * component
    * pages, routing
    * store (vuex)
    * common modules (session handling)
    * 환경에 따른 설정 관리 (dev, producting에서 가르키는 api 서버 주소 관리 등)
* component 및 page 작성해 보면서 wiki에 가이드 문서 작성

**Comment by ktk1012** [comment]
component와 page를 분리하자. (inspired from nuxt.js)
* component: ui에서 공통적으로 사용될 요소(navbar, item, ...). 해당 컴포넌트는 단순히 ui만 그려주는 역할. react에서 말하는 presentational component
* page: component를 조합하여 페이지를 그림, data fetching (혹은 store에서 mutation comit, action dispatch). 실제 route는 각 page들에 대한 url매핑으로 볼 수 있다.

**Comment by ktk1012** [comment]
클라이언트 설정은 https://webpack.js.org/plugins/define-plugin/ 을 참고해서 따라 가면 될듯. (현재 프로젝트에서는 config 폴더에 config.prod.js, config.dev.js 두 개 있고 dev가 prod 설정 덮어쓰므로 overriding은 dev에서 합니다.)
주의할 점은 vue component 혹은 page 의 vue template에 webpack plugin을 호출하는 실수를 범하면 안된다.. 만약 쓰고 싶으면 <script> 태그 안에서 data()로 호출하든지 해야 한다.. 템플릿 안에 쓰면 vue 템플릿 컴파일이 안됨

**Comment by ktk1012** [comment]
component는 prop을 받아서 로직을 처리하도록 (즉 상태는 전부 page에서 처리하고 그 상태를 prop으로 각 component에 내려준다. 이벤트도 prop으로 내려주는것이 좋을거 같다는 생각.. 
* http://realignist.me/code/2017/01/17/vue-js-best-practice.html
* https://vuejs-kr.github.io/jekyll/update/2017/03/13/vuejs-component-style-guide/

**Comment by ktk1012** [comment]
vuex 스토어의 액션은 항상 promise를 리턴하는게 좋을 듯 하다.
로직 상 특정 action (api request를 보내고 나서) page내에서 추가 로직 처리가 필요할 때가 있는데 (token을 localStorage에 넣는다거나, 로그아웃 이후 루트 페이지로 리다이렉트 한다거나 하는 등..) promise를 리턴해야 store내의 lifecycle hook에서 순서를 보장하기가 쉽다.

**Comment by ktk1012** [comment]
https://router.vuejs.org/kr/essentials/passing-props.html
vue router에서 라우팅 할 때 라우터 정보 (query param)를 page에서 data() 메서드를 통해서 정보를 해당 page 내에서 사용하도록 하는데, prop으로 전달하도록 변경합니다. prop으로 명시적으로 각 page에서 어떤 route 파라미터를 쓴다는걸 지정할 수 있고 현재 구조는 page가 router에 의존하게 되니 의존성 해소 측면에서도 좋습니다.

**Comment by Shavakan** [comment]
#36 과 마찬가지로 PR #38 이 머지되었으므로 닫습니다.
