### ISSUE TITLE
Front-end를 위한 공통 모듈 작성

### ISSUE THREAD

**Issue by ktk1012** [sparcs-kaist/sparcs09#35]
* 프론트 엔드에서 공통적으로 쓰일 요소들을 미리 모듈로 작성
    * session 관리 (페이지를 로드 했을 때 session storage에 토큰이 있는지 확인, 로그인 했을 때 토큰 session storage에 저장)
    * api 호출 (get, post 호출 할 때 session 정보를 중간에 담아서 보낸다. 응답 값에 따른 예외 페이지 작성 (404, 403 등))

해당 이슈 진행하면서 #34 의 wiki 가이드 작성 진행 예정

**Comment by samjo-nyang** [comment]
vue-resource: http client for vue (https://github.com/pagekit/vue-resource)

**Comment by ktk1012** [comment]
vue-resource or axios를 사용할 예정입니다. (아마 vue와 친화력이 좋은 vue-resource를 사용하지 않을까 싶습니다만은..)

**Comment by ktk1012** [comment]
* session 관리 이슈는 #36에서 진행합니다.

**Comment by ktk1012** [comment]
* 유틸리티 함수는 utils 디렉토리에 작성합니다.
* 현재 sparcs sso 관련 헬퍼 함수 utils/sparcs-sso.js 에 작성
* utils에 api-client.js 작성해서 axios에 설정 추가한 wrapper 작성 중

**Comment by ktk1012** [comment]
vue-resource에 대해서 알아보자
* https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4
그만 알아보도록 하자. axios를 씁시다.

**Comment by ktk1012** [comment]
PR 머지되었으므로 Close 처리 합니다.
