### ISSUE TITLE
Client side auth login 구현

### ISSUE THREAD

**Issue by ktk1012** [sparcs-kaist/sparcs09#36]
Sparcs sso에서 토큰을 발급받고 이를 sparcs09 에서 사용할 토큰으로 변환하여 저장합니다.
구현할 항목은 다음과 같습니다.

1. sso login및 로그인 결과 검증 (state가 일치하는지)
2. 검증 실패 시 ->  에러 페이지 띄우기
3. 검증 완료 시 -> sparcs09 서버에 sso토큰을 전송함 (api에서 해당하는 엔드포인트가 필요합니다.)
4. sparcs09에서 검증 완료되었을 시 발급 받은 09 토큰을 받고 이를 session storage에 저장
5. 새 탭으로 sparcs09 접속 했을 때 -> Vue instance init시 session storage에 토큰 있는지 확인하여 로드

**Comment by ktk1012** [comment]
https://github.com/nuxt/example-auth0 로그인 관련한 참고 자료.

**Comment by samjo-nyang** [comment]
1. 로그인 url은 다음 링크를 참조하여 build하시면 됩니다. 보안을 위해 state는 32bit 이상 되도록 해주시기 바랍니다. [링크](https://wiki.sparcs.org/w/index.php/SPARCS_SSO/API_%EB%AA%85%EC%84%B8#Auth_Token_Require)
2. 3번 단계에서 api에서 해당하는 endpoint는 `POST /api/session/`입니다.

**Comment by ktk1012** [comment]
* login page 를 만들어서 리다이렉트 (window.location.href 변경..) 후 code리턴 받은 것 까지 확인.
* 웹 프론트 초짜라 sso login url 및 client_id 같은 빌드 타임에 필요한 설정을 어떻게 관리하는지 몰라서 고민중... (서버면 그냥 settings 파일이 있으면 되는데 웹은 어떠케 할지 ㅠㅠ)

**Comment by ktk1012** [comment]
* 설정 관리는 webpack definePlugin으로 sso 서버 접근 정보와 버전 정보 client id 정보 설정
* auth/signin url로 이동하면 mounted 이후 sparcs sso 서버로 리다이렉트 
* auth/login-callback 으로 redirect 돌아오면서 state 값 비교, 값 다르면 error page로 이동 (/error)
    * 404, 403 등등 에러페이지는 어떻게 관리해야 할지 아직 잘 모르겠다.
* 이제 vuex store로 sparcs09 api에 code 보내서 token 값 저장하는 것 구현 하면 얼추 될듯

**Comment by Shavakan** [comment]
PR #38 이 develop 브랜치에 머지되었으므로 닫습니다.
자동으로 닫힐 줄 알았는데 안닫히네요. 커밋메시지를 (done #34, #35, #36) 이렇게 써서 그런가...
