### ISSUE TITLE
개발 가이드 초기 설정 작성

### ISSUE THREAD

**Issue by Shavakan** [sparcs-kaist/sparcs09#42]
매번 할 때마다 간격이 길다보니 어떤 작업들을 해줘야 하는지 자꾸 까먹네요...

SPARCS SSO 특성 상 개발자마다 환경 설정 등을 해줘야 하는 부분들이 있는데 간단하게 보면서 따라할 수 있는 문서를 만들어 두는게 나을 것 같습니다.

지금 존재하는 README.md를 고치는게 적절할 것 같습니다.

**Comment by Shavakan** [comment]
Introduction
---

1. You need to setup [SPARCS SSO](https://sparcssso.kaist.ac.kr/dev/main/) configurations for development.

2. You need to run both the API Server (Django) and Web (Vue.js) in development configurations.

SPARCS SSO
---

**Add a SPARCS SSO Test Service**

 - Main URL: http://localhost:8080
 - Login Callback URL: http://localhost:8080/auth/login_callback
 - Unregister URL: http://localhost:8080/auth/unregister (현재 미구현)

Web (Vue.js)
---

- config/index.js:

```
module.exports = {
  ...
  dev: {
    ...
    port: [WEB_PORT],
    ...
    proxyTable: {
      "/api": {
        target: "http://localhost:[API_PORT]/api',
        ...
      }
    }
  }
}
```

- config/dev.env.js

```
module.export = merge(prodEnv, {
  NODE_ENV: '"development"',
  SSO_CLIENT_ID: '"[SPARCS SSO Client ID]"',
  SPARCS09_API_DOMAIN: '"[http://127.0.0.1:[WEB_PORT]/api/"',
}
```

**Run Vue**

```
$ npm run dev
 node build/dev-server.js

[HPM] Proxy created: /api  ->  http://localhost:16134/api
[HPM] Proxy rewrite rule created: "^/api" ~> ""
> Starting dev server...

| DONE | Compiled successfully in xxxx ms                                                               HH:mm:ss


> Listening at http://localhost:[WEB_PORT]
```


API (Django)
---

- settings.py:

```
SSO_ID = [SPARCS SSO Test Service Client Id]
SSO_KEY= [SPARCS SSO Test Service Secret Key]

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]
```

**Create Virtual Python Environment**

Download [virtualenvwrapper](http://virtualenvwrapper.readthedocs.io/en/latest/install.html)

```
$ mkvirtualenv -p python3 sparcs09
$ workon sparcs09
```

Check your local machine's python version if `mkvirtualenv -p` option fails

**Install Python Dependencies (if haven't done so)**
```
(sparcs09) $ pip install -r requirements.txt
```

**API Database Migrate**
```
(sparcs09) $ python manage.py makemigrations
(sparcs09) $ python manage.py migrate
```

**Run API Server**
```
(sparcs09) $ python manage.py runserver 0.0.0.0:[API_PORT]
Performing system checks...

System check identified no issues (0 silenced).
July 18, 2017 - 15:20:28
Django version 1.11.2, using settings 'sparcs09.settings'
Starting development server at http://0.0.0.0:[API_PORT]/
Quit the server with CTRL-BREAK.
```

**Comment by Shavakan** [comment]
@sugoiii 한 번 따라해보시고 PR #38 리뷰해보세요.
하다가 문제가 있으면 알려주세용

**Comment by sugoiii** [comment]
정말 사소한 것들이지만
- config/dev.env.js 부분에 [가 오타로 있는것 같아요!
- npm run dev 전에 npm install이 있으면 조금 더 친절해질 것 같아요..

그나저나 안되네요ㅠㅠㅠ

**Comment by Shavakan** [comment]
수정했습니당. 어느 부분에서 안되고 있어요?

**Comment by Shavakan** [comment]
개발자 도구를 열어보고 어떤 에러가 나고 있는지 알려줄래요?

**Comment by sugoiii** [comment]
XMLHttpRequest cannot load http://127.0.0.1:12345/api/sessions/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12345' is therefore not allowed access.

이라고 합니다!

**Comment by Shavakan** [comment]
API DOMAIN이 WEB PORT로 설정되어 있는지 확인해볼래요?

**Comment by sugoiii** [comment]
넵 맞게 되어 있어요!

**Comment by ktk1012** [comment]
12345가 혹시 api 서버 포트인가요? 현재 API_DOMAIN에서 port 설정은 front-end 서버 설정을 따라갑니다..

**Comment by Shavakan** [comment]
@sugoiii 커밋한 브랜치에 본인 설정이 어떻게 되어있는지가 빠져있어서 문제 파악이 어렵습니다 ㅋㅋㅋㅋ 설정한 내용도 같이 커밋해주세요

**Comment by samjo-nyang** [comment]
그냥 기본값 넣어놓고 process.env.XXX로 환경변수에서 가져오도록 바꾸면 좋을거 같아여
