### ISSUE TITLE
add a new query method to GET /items/ API

### ISSUE THREAD

**Issue by samjo-nyang** [sparcs-kaist/sparcs09#48]
add a new optional query method to GET /items/ API
- joined_status (NONE, PENDING, JOINED, PAID, CONFIRMED and/or DONE)
- can be multiple, separated by comma
- please discuss name, and its detail status in today meeting

**Comment by Shavakan** [comment]
7/19일 회의에서 논의한 바로는 다음과 같이 변경하기로 결정하였는데, @samjo-nyang 님 의도가 반영되었는지 확인해주세요.

파라미터 명 같은게 맞는지 모르겠네요 위키가 죽어서 회의록 확인이 어려워서...

잘못된거 있으면 그냥 코멘트 수정해주세요.

**GET /items/**

**Parameters**

- _limit_: Number, Default: 10.
Sets maximum number of returned items.

- _offset_: Number, Default: 0.
Sets number of items to skip (for paging).

(removed parameters)

- _live\_only_: Boolean, Default: true.
Flag to query only ongoing items. Replaced by _status_ parameter.

(new parameters)

- _status_: Number, Default: 0.
Sets the status of items to query. Value obtained by logical OR operation of Item.status ENUM values.

- _sid_: String, Default: None.
Sets the query with respect to a user. Permission validated by the server.

**Comment by samjo-nyang** [comment]
네, 대충 방향은 맞는거 같네요. 다만 질문이 좀 있습니다.
1. 관리자만 sid param을 사용하나요?
2. Item.Status는 현재 Open=0과 Closed=1밖에는 (그것도 문자열로 되어있음) 없습니다만... Payment.Status 까지 합쳐서 (Not Join=1, Pending=2, Paid=4, Closed=8)로 해야 하지 않을지요?
3. 지금 Item, Content, Payment에서 enum field가 모두 integer가 아닌 char로 되어있습니다. 수정이 필요해보이는데 이것도 회의때 논의되었는지요

**Comment by sugoiii** [comment]
앗 회의록을 늦게 작성했더니 이렇게 작성해 주셨네요ㅠㅠㅠㅠ
적절한 답변일지는 모르겠지만
1. sid param의 경우에는 일반 유저도 자신의 sid에 한해서 사용을 할 것 같아요!
2.,3 -> 넵넵 회의 때 전부 말씀하신 방식으로 바꾸기로 얘기 했었어요! 회의록에 더 자세히 작성 하겠습니당

**Comment by Shavakan** [comment]
@samjo-nyang 
1. 아닙니다. 저건 "내가 참여한 공동구매"였나 뭐 이런걸 조회하기 위해서 추가한걸로 기억합니다. sid가
 request를 요청하는 user에 해당하는 sid에 해당하는지 서버에서 검증이 필요하지 않을까 싶습니다.

**Comment by samjo-nyang** [comment]
@Shavakan @sugoiii 댓글 수정했습니다. 이 스펙이면 괜찮을까요?

**Comment by Shavakan** [comment]
@samjo-nyang A user (including hosts) can only set query as None or the user sid.
가 무슨 말인지 모르겠어요. 일단은 괜찮아보입니다.

**Comment by samjo-nyang** [comment]
영어 알못이라... None으로 쿼리하거나 본인의 sid로만 쿼리 가능하다는 뜻입니당

**Comment by Shavakan** [comment]
어차피 Optional 파라미터니까 그냥 본인의 sid로만 쿼리 가능하다고만 적으면 될 것 같습니당

**Comment by samjo-nyang** [comment]
Spec 문서 업데이트하겠습니다.

**Comment by Shavakan** [comment]
업데이트하고 닫아주세용

**Comment by Shavakan** [comment]
프로젝트에서도 옮겨주세용
