### ISSUE TITLE
Update core models

### ISSUE THREAD

**Issue by Shavakan** [sparcs-kaist/sparcs09#49]
7/19 회의 내용에 따라 모델을 업데이트해야 합니다.

**Item**
메인 화면 및 리스트 구성을 위해 이미지 썸네일, 설명이 필수로 들어가야 합니다.
뭔가 status? type? 관련한 내용도 있었던 것 같은데 정작 모델을 보니까 그런게 없네요... 뭐였지...

**Content**
회의시간에 나온 내용은 아닌데 이제 보니까 type이 파이썬 키워드입니다.
크게 상관은 없지만 기분이 나쁘니까 kind 같은걸로 바꾸면 어떨까요?

**Comment by samjo-nyang** [comment]
1. Item.description를 하나 추가 vs 첫번째 content의 내용 두 가지 방법이 있을 것 같습니다. 어느걸로 할지 (또는 둘 다 할지)는 논의가 더 필요해보입니다.
2. Item.thumbnail 추가는 필요하다고 생각합니다.
3. Item.status? type?은 공동구매 수요조사와 관련되어 언급되었던걸로 기억합니다. 오버스펙이라 도입하지 않은 것으로 알고 있습니다.
4. Content.type -> Content.kind로 변경했으면 좋겠습니다. syntax highlighting이 거슬리네요

**Comment by samjo-nyang** [comment]
의견 다시 구합니다 - @Shavakan @ktk1012 @sugoiii 
1. item.description은 선택 (입력 안할 시 첫번째 content의 내용으로 자동 채워짐)
2. item.thumbnail 추가
3. item.status, type 무시
4. content.type -> content.kind로 변경해서 models.py 업데이트 할까요?
