### ISSUE TITLE
로깅 - 수행

### ISSUE THREAD

**Issue by samjo-nyang** [sparcs-kaist/sparcs09#8]
모든 행위에 로깅 코드 추가
- 로깅 구조(위계)에 대해 생각해야 함
- ex: sparcs09.buy -> sparcs09.buy.join / sparcs09.group / sparcs09.group.make /
- sparcs sso 로깅 구조 참고

**Comment by ktk1012** [comment]
모든 request로깅 같은건 middleware로 처리 할 수 있지 않을까요? [doc](https://docs.djangoproject.com/en/1.11/topics/http/middleware/) 파라미터 까지 같이 로깅 한다 치면 조금 복잡해 질수는 있을 것 같지만..

**Comment by samjo-nyang** [comment]
Feature 개발과 동시에 로깅 코드도 같이 넣는걸로 하겠습니다.

**Comment by samjo-nyang** [comment]
이슈 닫습니다.
